### ISSUE TITLE
Ruby gem does not support the geocode API

### ISSUE THREAD

**Issue by yholkamp** [petewarden/dstk#25]
I noticed that the Ruby gem does not currently support the Google-style Geocoder method. As with #24 I'm not sure where the code can be found so I'm not able to submit a pull request. In any case, adding support for this method should be as simple as incorporating the following:

```
  def geocode(text)
    response = json_api_call('/maps/api/geocode/json', {"address" => text})
    response
  end
```

**Comment by campeterson** [comment]
https://github.com/petewarden/dstk/pull/26
