### ISSUE TITLE
Unexpected Google-style geocoding results

### ISSUE THREAD

**Issue by yholkamp** [petewarden/dstk#28]
During some testing I noticed that for some strings the results produced by the Google-style geocoder of the dstk API are at least somewhat unexpected.

For example, the following string: 

```
28 2nd St, San Francisco, CA 94105, USA
```

Results in [a response](http://www.datasciencetoolkit.org/maps/api/geocode/json?address=28%202nd%20St%2C%20San%20Francisco%2C%20CA%2094105%2C%20USA) that shows a location somewhere on the border between Turkey and Syria, while [Google is able to geocode this properly](http://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=28%202nd%20St,%20San%20Francisco,%20CA,%2094105,%20USA).

As a workaround I noticed that removing the ', USA' part restores the output to the expected value but it would be great if the geocoder also works when using a more international format.

**Comment by yholkamp** [comment]
Another example which appears to be broken under certain circumstances: [1600 Amphitheatre Parkway, Mountain View, CA, United States](http://www.datasciencetoolkit.org/maps/api/geocode/json?address=1600%20Amphitheatre%20Parkway%2C%20Mountain%20View%2C%20CA%2C%20United%20States) returns the info for some place in NC rather than CA. On the other hand the query [1600 Amphitheatre Parkway, Mountain View, CA](http://www.datasciencetoolkit.org/maps/api/geocode/json?address=1600%20Amphitheatre%20Parkway%2C%20Mountain%20View%2C%20CA) produces the correct result.

**Comment by petewarden** [comment]
Thanks for the report, it's much appreciated! I've put in a fix for both of these cases. The code wasn't stripping out the country suffix, and that was causing the street-level geocoder to get confused.

This does highlight a couple of examples where the geocoder is being over-eager - in both cases it would be preferable to return no results than ones as erroneous as North Carolina or Turkey!

**Comment by yholkamp** [comment]
Thanks for the quick fix and your great work @petewarden, I much appreciate it!
