### ISSUE TITLE
geodictapi/geodictdata repos referenced in docs/serversetup.txt are missing

### ISSUE THREAD

**Issue by ryanwitt** [petewarden/dstk#9]
I'm following these instructions to get dstk running on an existing machine.

**Comment by petewarden** [comment]
Sorry Ryan, those should be dstk and dstkdata respectively. I've updated the instructions, let me know how that goes.

**Comment by ryanwitt** [comment]
thanks!

## 

Ryan Witt
Founder, Opani

**Comment by ryanwitt** [comment]
serversetup.txt now works for me, thanks, Pete. Closed by c6821819f22ba42d318d0ccfbb1c54c8104b0eb7
